/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      keyframes: {
        wave: {
          '0%': { transform: 'rotate(0.0deg)' },
          '50%': { transform: 'rotate(10deg)' },
          '100%': { transform: 'rotate(-10.0deg)' },
        },
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
        wave: 'wave 15s ease-in-out infinite',
      },
      colors: {
        'pc-50': 'rgb(var(--pc-50) / <alpha-value>)',
        'pc-100': 'rgb(var(--pc-100) / <alpha-value>)',
        'pc-200': 'rgb(var(--pc-200) / <alpha-value>)',
        'pc-300': 'rgb(var(--pc-300) / <alpha-value>)',
        'pc-400': 'rgb(var(--pc-400) / <alpha-value>)',
        'pc-500': 'rgb(var(--pc-500) / <alpha-value>)',
        'pc-600': 'rgb(var(--pc-600) / <alpha-value>)',
        'pc-700': 'rgb(var(--pc-700) / <alpha-value>)',
        'pc-800': 'rgb(var(--pc-800) / <alpha-value>)',
        'pc-900': 'rgb(var(--pc-900) / <alpha-value>)',
        'fc-50': 'rgb(var(--fc-50) / <alpha-value>)',
        'fc-100': 'rgb(var(--fc-100) / <alpha-value>)',
        'fc-200': 'rgb(var(--fc-200) / <alpha-value>)',
        'fc-300': 'rgb(var(--fc-300) / <alpha-value>)',
        'fc-400': 'rgb(var(--fc-400) / <alpha-value>)',
        'fc-500': 'rgb(var(--fc-500) / <alpha-value>)',
        'fc-600': 'rgb(var(--fc-600) / <alpha-value>)',
        'fc-700': 'rgb(var(--fc-700) / <alpha-value>)',
        'fc-800': 'rgb(var(--fc-800) / <alpha-value>)',
        'fc-900': 'rgb(var(--fc-900) / <alpha-value>)',
        'sc-50': 'rgb(var(--sc-50) / <alpha-value>)',
        'sc-100': 'rgb(var(--sc-100) / <alpha-value>)',
        'sc-200': 'rgb(var(--sc-200) / <alpha-value>)',
        'sc-300': 'rgb(var(--sc-300) / <alpha-value>)',
        'sc-400': 'rgb(var(--sc-400) / <alpha-value>)',
        'sc-500': 'rgb(var(--sc-500) / <alpha-value>)',
        'sc-600': 'rgb(var(--sc-600) / <alpha-value>)',
        'sc-700': 'rgb(var(--sc-700) / <alpha-value>)',
        'sc-800': 'rgb(var(--sc-800) / <alpha-value>)',
        'sc-900': 'rgb(var(--sc-900) / <alpha-value>)',
        'tc-50': 'rgb(var(--tc-50) / <alpha-value>)',
        'tc-100': 'rgb(var(--tc-100) / <alpha-value>)',
        'tc-200': 'rgb(var(--tc-200) / <alpha-value>)',
        'tc-300': 'rgb(var(--tc-300) / <alpha-value>)',
        'tc-400': 'rgb(var(--tc-400) / <alpha-value>)',
        'tc-500': 'rgb(var(--tc-500) / <alpha-value>)',
        'tc-600': 'rgb(var(--tc-600) / <alpha-value>)',
        'tc-700': 'rgb(var(--tc-700) / <alpha-value>)',
        'tc-800': 'rgb(var(--tc-800) / <alpha-value>)',
        'tc-900': 'rgb(var(--tc-900) / <alpha-value>)',
        dark1: '#1F2937',
        dark2: '#334155',
        dark3: '#475569',
        light1: '#ffffff',
        light2: '#cccccc',
      },
    },
  },
  plugins: [],
};
